# Generated by Django 3.0.3 on 2020-02-16 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Feature',
            field=models.BooleanField(default=True),
        ),
    ]
